using System.Collections.Generic;

public static class SkinConstants
{
        public enum RequestMode
    {
        None,
        SelectSkin,
        GenerateSkin
    }


    public static readonly Dictionary<string, string> skinDescriptionToSkinFile = new Dictionary<string, string> {
        {"fantasyMaleB", "fantasyMaleB.png"},
        {"fantasyMaleA", "fantasyMaleA.png"},
        {"military female green", "militaryFemaleA.png"},
        {"military female brown", "militaryFemaleB.png"},
        {"racer purple female", "racerPurpleFemale.png"},
        {"alien light-blue", "alienC.png"},
        {"alien green-yellow", "alienB.png"},
        {"alien teal", "alienA.png"},
        {"astronaut male orange", "astroMaleB.png"},
        {"fantasyFemaleB", "fantasyFemaleB.png"},
        {"cyborgFemaleA", "cyborgFemaleA.png"},
        {"cyborg", "cyborg.png"},
        {"farmer blue-white", "farmerA.png"},
        {"astronaut male grey", "astroMaleA.png"},
        {"fantasyFemaleA", "fantasyFemaleA.png"},
        {"athleteMaleRed", "athleteMaleRed.png"},
        {"racerBlueMale", "racerBlueMale.png"},
        {"athleteFemaleYellow", "athleteFemaleYellow.png"},
        {"racerOrangeMale", "racerOrangeMale.png"},
        {"farmer grey-red", "farmerB.png"},
        {"athleteFemaleBlue", "athleteFemaleBlue.png"},
        {"robot2", "robot2.png"},
        {"robot3", "robot3.png"},
        {"racer Red Female", "racerRedFemale.png"},
        {"racer Orange Female", "racerOrangeFemale.png"},
        {"racer Red Male", "racerRedMale.png"},
        {"athlete Male Green", "athleteMaleGreen.png"},
        {"criminalMaleA", "criminalMaleA.png"},
        {"athleteMaleYellow", "athleteMaleYellow.png"},
        {"racerPurpleMale", "racerPurpleMale.png"},
        {"robot", "robot.png"},
        {"military male green", "militaryMaleB.png"},
        {"athlete Female Red", "athleteFemaleRed.png"},
        {"military male brown", "militaryMaleA.png"},
        {"casualFemaleA", "casualFemaleA.png"},
        {"zombie angry", "zombieA.png"},
        {"businessMaleA", "businessMaleA.png"},
        {"skaterFemaleA", "skaterFemaleA.png"},
        {"casualFemaleB", "casualFemaleB.png"},
        {"skaterMaleA", "skaterMaleA.png"},
        {"zombie hair", "zombieB.png"},
        {"businessMaleB", "businessMaleB.png"},
        {"racerGreenFemale", "racerGreenFemale.png"},
        {"athlete Male Blue", "athleteMaleBlue.png"},
        {"zombie skull", "zombieC.png"},
        {"athlete Female Green", "athleteFemaleGreen.png"},
        {"astronaut female grey", "astroFemaleA.png"},
        {"survivorMaleB", "survivorMaleB.png"},
        {"racerGreenMale", "racerGreenMale.png"},
        {"survivorFemaleA", "survivorFemaleA.png"},
        {"racerBlueFemale", "racerBlueFemale.png"},
        {"casualMaleB", "casualMaleB.png"},
        {"astronaut female orange", "astroFemaleB.png"},
        {"survivorMaleA", "survivorMaleA.png"},
        {"survivorFemaleB", "survivorFemaleB.png"},
        {"casualMaleA", "casualMaleA.png"}
    };

    public static readonly Dictionary<string, int> skinFileToID = new Dictionary<string, int> {
        {"alienA.png", 0},
        {"alienB.png", 1},
        {"alienC.png", 2},
        {"astroFemaleA.png", 3},
        {"astroFemaleB.png", 4},
        {"astroMaleA.png", 5},
        {"astroMaleB.png", 6},
        {"athleteFemaleBlue.png", 7},
        {"athleteFemaleGreen.png", 8},
        {"athleteFemaleRed.png", 9},
        {"athleteFemaleYellow.png", 10},
        {"athleteMaleBlue.png", 11},
        {"athleteMaleGreen.png", 12},
        {"athleteMaleRed.png", 13},
        {"athleteMaleYellow.png", 14},
        {"businessMaleA.png", 15},
        {"businessMaleB.png", 16},
        {"casualFemaleA.png", 17},
        {"casualFemaleB.png", 18},
        {"casualMaleA.png", 19},
        {"casualMaleB.png", 20},
        {"criminalMaleA.png", 21},
        {"cyborg.png", 22},
        {"cyborgFemaleA.png", 23},
        {"fantasyFemaleA.png", 24},
        {"fantasyFemaleB.png", 25},
        {"fantasyMaleA.png", 26},
        {"fantasyMaleB.png", 27},
        {"farmerA.png", 28},
        {"farmerB.png", 29},
        {"militaryFemaleA.png", 30},
        {"militaryFemaleB.png", 31},
        {"militaryMaleA.png", 32},
        {"militaryMaleB.png", 33},
        {"racerBlueFemale.png", 34},
        {"racerBlueMale.png", 35},
        {"racerGreenFemale.png", 36},
        {"racerGreenMale.png", 37},
        {"racerOrangeFemale.png", 38},
        {"racerOrangeMale.png", 39},
        {"racerPurpleFemale.png", 40},
        {"racerPurpleMale.png", 41},
        {"racerRedFemale.png", 42},
        {"racerRedMale.png", 43},
        {"robot.png", 44},
        {"robot2.png", 45},
        {"robot3.png", 46},
        {"skaterFemaleA.png", 47},
        {"skaterMaleA.png", 48},
        {"survivorFemaleA.png", 49},
        {"survivorFemaleB.png", 50},
        {"survivorMaleA.png", 51},
        {"survivorMaleB.png", 52},
        {"zombieA.png", 53},
        {"zombieB.png", 54},
        {"zombieC.png", 55}
    };
}
